apiVersion: v1
kind: Secret
metadata:
  name: htpasswd-secret
  namespace: registry
type: Opaque
stringData:
  htpasswd: ondrej.web@gmail.com:$2y$05$OHZTOF4KjPQFXEdM8jsxjOq3Q2ROaSokzzNw2Rnx4DCmtT7tHmXge
